# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c8b68a5d08583ce19c23a39ab9310791ef07330d4ea5c68a576aaf0bbf7f902b32c8377ac7fdd7285a1497711f605bcb9bb25bee39c9ececa735745e28b0967

test:
  secret_key_base: 4b5d81a6c9510b2075dc446be4298f8629181962fb181ef1195fd8f31ce0f06f07f5eee2a5c1424030f3eaa40f1c33a2ed3186908f293504504106c44d068eb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
